services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube_daw
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - ../sonarqube_data:/opt/sonarqube/data
      - ../sonarqube_extensions:/opt/sonarqube/extensions
      - ../sonarqube_logs:/opt/sonarqube/logs